// src/config/syllabusData.ts
import { SectionSyllabus } from '../types/syllabus';

export const SYLLABUS_SECTIONS: SectionSyllabus[] = [
  {
    id: 'english',
    name: 'English Language',
    isOfficialName: true,
    questionCount: 50,
    marks: 50,
    topics: [
      {
        id: 'eng_rc',
        name: 'Reading Comprehension',
        sectionId: 'english',
        priority: 'VERY HIGH',
        practiceGuideline: '8-12 passages/week',
        revisionGuideline: 'Every 3-4 days',
        subtopics: [
          { id: 'eng_rc_1', name: "Main idea / Central theme", isOfficial: false },
          { id: 'eng_rc_2', name: "Author's purpose", isOfficial: false },
          { id: 'eng_rc_3', name: 'Tone & attitude', isOfficial: false },
          { id: 'eng_rc_4', name: 'Inference', isOfficial: false },
          { id: 'eng_rc_5', name: 'Conclusion', isOfficial: false },
          { id: 'eng_rc_6', name: 'Fact vs Opinion', isOfficial: false },
          { id: 'eng_rc_7', name: 'Argument structure', isOfficial: false },
          { id: 'eng_rc_8', name: 'Evidence evaluation', isOfficial: false },
          { id: 'eng_rc_9', name: 'Contextual meaning', isOfficial: false },
          { id: 'eng_rc_10', name: 'Passage vocabulary', isOfficial: false },
          { id: 'eng_rc_11', name: 'Logical implications', isOfficial: false },
        ],
      },
      {
        id: 'eng_vocab',
        name: 'Vocabulary',
        sectionId: 'english',
        priority: 'HIGH',
        practiceGuideline: '20-30 words/day + practice',
        revisionGuideline: 'Every 5-7 days',
        subtopics: [
          { id: 'eng_vocab_1', name: 'Synonyms & Antonyms', isOfficial: false },
          { id: 'eng_vocab_2', name: 'One-word substitutions', isOfficial: false },
          { id: 'eng_vocab_3', name: 'Idioms & Phrases', isOfficial: false },
          { id: 'eng_vocab_4', name: 'Contextual vocabulary', isOfficial: false },
          { id: 'eng_vocab_5', name: 'Confusing/similar words', isOfficial: false },
          { id: 'eng_vocab_6', name: 'Word usage', isOfficial: false },
          { id: 'eng_vocab_7', name: 'Prefixes & Suffixes', isOfficial: false },
          { id: 'eng_vocab_8', name: 'Word roots (high-utility)', isOfficial: false },
        ],
      },
      {
        id: 'eng_grammar',
        name: 'Grammar',
        sectionId: 'english',
        priority: 'HIGH',
        practiceGuideline: '30-40 Qs/week',
        revisionGuideline: 'Weekly',
        subtopics: [
          { id: 'eng_gram_1', name: 'Parts of speech overview', isOfficial: false },
          { id: 'eng_gram_2', name: 'Nouns, Pronouns, Verbs', isOfficial: false },
          { id: 'eng_gram_3', name: 'Adjectives & Adverbs', isOfficial: false },
          { id: 'eng_gram_4', name: 'Tenses', isOfficial: false },
          { id: 'eng_gram_5', name: 'Subject-Verb Agreement', isOfficial: false },
          { id: 'eng_gram_6', name: 'Articles, Prepositions, Conjunctions', isOfficial: false },
          { id: 'eng_gram_7', name: 'Modifiers', isOfficial: false },
          { id: 'eng_gram_8', name: 'Active-Passive Voice', isOfficial: false },
          { id: 'eng_gram_9', name: 'Direct-Indirect Narration', isOfficial: false },
          { id: 'eng_gram_10', name: 'Parallelism', isOfficial: false },
          { id: 'eng_gram_11', name: 'Sentence correction', isOfficial: false },
          { id: 'eng_gram_12', name: 'Error spotting', isOfficial: false },
        ],
      },
      {
        id: 'eng_verbal',
        name: 'Verbal Ability',
        sectionId: 'english',
        priority: 'MEDIUM',
        practiceGuideline: '15-20 sets/week (Para jumbles)',
        revisionGuideline: 'Weekly',
        subtopics: [
          { id: 'eng_va_1', name: 'Fill in the blanks', isOfficial: false },
          { id: 'eng_va_2', name: 'Sentence completion', isOfficial: false },
          { id: 'eng_va_3', name: 'Para jumbles', isOfficial: false },
          { id: 'eng_va_4', name: 'Sentence rearrangement', isOfficial: false },
          { id: 'eng_va_5', name: 'Odd sentence out', isOfficial: false },
          { id: 'eng_va_6', name: 'Logical sentence sequence', isOfficial: false },
        ],
      },
    ],
  },
  {
    id: 'ca_gk',
    name: 'Current Affairs & General Knowledge',
    isOfficialName: true,
    questionCount: 30,
    marks: 30,
    topics: [
      {
        id: 'ca_core',
        name: 'Current Affairs (last 8-10 months)',
        sectionId: 'ca_gk',
        priority: 'VERY HIGH',
        practiceGuideline: 'Daily + weekly compilation',
        revisionGuideline: 'Weekly + monthly',
        subtopics: [
          { id: 'ca_1', name: 'National: Govt schemes, Bills & Acts, Policies, Judiciary, Appointments', isOfficial: false },
          { id: 'ca_2', name: 'International: UN, G20, BRICS, SCO, NATO, Summits & Conflicts', isOfficial: false },
          { id: 'ca_3', name: 'Economy: RBI, Monetary policy, Inflation, GDP, Budget highlights', isOfficial: false },
          { id: 'ca_4', name: 'Science & Technology: ISRO missions, AI, Defence tech', isOfficial: false },
          { id: 'ca_5', name: 'Environment: Climate change, COP, Biodiversity, National parks', isOfficial: false },
        ],
      },
      {
        id: 'ca_static_gk',
        name: 'Static GK (Polity, History, Geography, Economy basics)',
        sectionId: 'ca_gk',
        priority: 'MEDIUM',
        practiceGuideline: 'Topic-wise notes + 20 Qs',
        revisionGuideline: 'Fortnightly',
        subtopics: [
          { id: 'gk_1', name: 'Indian Polity (Constitution, Parliament, Judiciary, Executive)', isOfficial: false },
          { id: 'gk_2', name: 'Ancient, Medieval & Modern Indian History', isOfficial: false },
          { id: 'gk_3', name: 'Indian & World Geography', isOfficial: false },
          { id: 'gk_4', name: 'Economy basics & Science basics', isOfficial: false },
          { id: 'gk_5', name: 'Environment, Art & Culture', isOfficial: false },
          { id: 'gk_6', name: 'Capitals, Currencies & International Organisations', isOfficial: false },
          { id: 'gk_7', name: 'Books & Authors, Important Days, Inventions', isOfficial: false },
        ],
      },
      {
        id: 'ca_lists',
        name: 'Awards, Sports & Science Lists',
        sectionId: 'ca_gk',
        priority: 'LOW',
        practiceGuideline: 'Monthly revision only (low ROI if overdone)',
        revisionGuideline: 'Monthly',
        subtopics: [
          { id: 'ca_list_1', name: 'Sports: Major Tournaments, Winners, Athletes, Records', isOfficial: false },
          { id: 'ca_list_2', name: 'Awards: Nobel, Bharat Ratna, Padma, Oscars, Booker, UNESCO', isOfficial: false },
        ],
      },
    ],
  },
  {
    id: 'logical',
    name: 'Logical Reasoning',
    isOfficialName: true,
    questionCount: 70,
    marks: 70,
    topics: [
      {
        id: 'lr_cr',
        name: 'Critical Reasoning (Assumptions, Strengthen/Weaken, Inference)',
        sectionId: 'logical',
        priority: 'VERY HIGH',
        practiceGuideline: '40-60 Qs/week',
        revisionGuideline: 'Every 3 days',
        subtopics: [
          { id: 'lr_cr_1', name: 'Arguments, Premises & Conclusions', isOfficial: false },
          { id: 'lr_cr_2', name: 'Assumptions', isOfficial: false },
          { id: 'lr_cr_3', name: 'Inference', isOfficial: false },
          { id: 'lr_cr_4', name: 'Strengthen / Weaken', isOfficial: false },
          { id: 'lr_cr_5', name: 'Cause and Effect', isOfficial: false },
          { id: 'lr_cr_6', name: 'Statement-Conclusion / Assumption / Argument', isOfficial: false },
          { id: 'lr_cr_7', name: 'Course of Action', isOfficial: false },
          { id: 'lr_cr_8', name: 'Assertion-Reason', isOfficial: false },
          { id: 'lr_cr_9', name: 'Analogy', isOfficial: false },
          { id: 'lr_cr_10', name: 'Principle / Application', isOfficial: false },
        ],
      },
      {
        id: 'lr_analytical_core',
        name: 'Syllogism + Arrangements + Puzzles',
        sectionId: 'logical',
        priority: 'VERY HIGH',
        practiceGuideline: '50-70 Qs/week',
        revisionGuideline: 'Every 3-4 days',
        subtopics: [
          { id: 'lr_an_1', name: 'Syllogism (all standard & negative types)', isOfficial: false },
          { id: 'lr_an_2', name: 'Linear Arrangement', isOfficial: false },
          { id: 'lr_an_3', name: 'Circular Arrangement', isOfficial: false },
          { id: 'lr_an_4', name: 'Seating Arrangement', isOfficial: false },
          { id: 'lr_an_5', name: 'Distribution, Selection & Grouping', isOfficial: false },
          { id: 'lr_an_6', name: 'Scheduling & Puzzles', isOfficial: false },
          { id: 'lr_an_7', name: 'Venn Diagrams', isOfficial: false },
          { id: 'lr_an_8', name: 'Logical Data Interpretation', isOfficial: false },
        ],
      },
      {
        id: 'lr_principle_facts',
        name: 'Principle + Facts (Pure Logic Application)',
        sectionId: 'logical',
        priority: 'HIGH',
        practiceGuideline: '20-30 Qs/week',
        revisionGuideline: 'Weekly',
        subtopics: [
          { id: 'lr_pf_1', name: 'Principle + Facts application', isOfficial: false },
          { id: 'lr_pf_2', name: 'Applying a stated principle strictly without external law', isOfficial: false },
          { id: 'lr_pf_3', name: 'Rule-based reasoning', isOfficial: false },
          { id: 'lr_pf_4', name: 'Identifying the logically correct outcome', isOfficial: false },
          { id: 'lr_pf_5', name: 'Reasoning strictly from given information', isOfficial: false },
        ],
      },
      {
        id: 'lr_analytical_misc',
        name: 'Series, Coding, Blood Relations, Directions',
        sectionId: 'logical',
        priority: 'MEDIUM',
        practiceGuideline: '20-30 Qs/week',
        revisionGuideline: 'Weekly',
        subtopics: [
          { id: 'lr_an_9', name: 'Blood Relations', isOfficial: false },
          { id: 'lr_an_10', name: 'Direction Sense', isOfficial: false },
          { id: 'lr_an_11', name: 'Coding-Decoding', isOfficial: false },
          { id: 'lr_an_12', name: 'Number Series & Letter Series', isOfficial: false },
          { id: 'lr_an_13', name: 'Ranking & Ordering', isOfficial: false },
        ],
      },
      {
        id: 'lr_avoid',
        name: 'Deep Legal Maxims / Case Laws / Mathematics',
        sectionId: 'logical',
        priority: 'AVOID',
        practiceGuideline: 'Skip (not required for AILET UG)',
        revisionGuideline: 'None',
        isAvoid: true,
        avoidReason:
          'OFFICIAL EXAM FACT: AILET UG requires NO prior legal knowledge, no case laws, no statutes, and has no Mathematics section. Legal principles appear purely as hypothetical rules to test logical application.',
        subtopics: [
          { id: 'lr_avoid_1', name: 'Case law memorization (Not in exam)', isOfficial: false },
          { id: 'lr_avoid_2', name: 'Latin legal maxims memorization (Not in exam)', isOfficial: false },
          { id: 'lr_avoid_3', name: 'Statutory sections / penal code memorization (Not in exam)', isOfficial: false },
          { id: 'lr_avoid_4', name: 'Mathematics / Quantitative Aptitude (No section in AILET)', isOfficial: false },
        ],
      },
    ],
  },
];
